export interface ExternalPaymentMethod {
  id: string;
  value: string;
}

export const EXTERNAL_PAYMENT_METHODS: ExternalPaymentMethod[] = [
  {id: 'external_interac', value: 'Interac'},
  {id: 'external_au_pay', value: 'au PAY'},
  {id: 'external_atone', value: 'atone'},
  {id: 'external_tng_ewallet', value: "Touch'n Go"},
  {
    id: 'external_softbank_carrier_payment',
    value: 'ソフトバンクまとめて支払い (Softbank carrier payments)',
  },
  {id: 'external_toss_pay', value: 'Toss Pay'},
  {id: 'external_laybuy', value: 'Laybuy'},
  {id: 'external_bank_pay', value: 'Bank Pay'},
  {
    id: 'external_au_easy_payment',
    value: 'auかんたん決済 (au easy payments)',
  },
  {id: 'external_bitcash', value: 'BitCash'},
  {id: 'external_azupay', value: 'Azupay'},
  {id: 'external_dbarai', value: 'd払い (d-barai)'},
  {id: 'external_famipay', value: 'FamiPay'},
  {id: 'external_gcash', value: 'GCash'},
  {id: 'external_grabpay_later', value: 'GrabPay Later'},
  {id: 'external_momo', value: 'MoMo'},
  {id: 'external_net_cash', value: 'NET CASH'},
  {id: 'external_octopus', value: 'Octopus'},
  {id: 'external_paidy', value: 'Paidy'},
  {id: 'external_paypay', value: 'PayPay'},
  {id: 'external_planpay', value: 'PlanPay'},
  {id: 'external_pay_easy', value: 'ペイジー (Pay-easy)'},
  {id: 'external_rakuten_pay', value: '楽天ペイ (Rakuten Pay)'},
  {id: 'external_merpay', value: 'メルペイ (Merpay)'},
  {id: 'external_webmoney', value: 'WebMoney'},
  {id: 'external_shopback_pay', value: 'Shopback Pay'},
  {id: 'external_aplazame', value: 'Aplazame'},
  {id: 'external_bizum', value: 'Bizum'},
  {id: 'external_divido', value: 'Divido'},
  {id: 'external_fonix', value: 'Fonix'},
  {id: 'external_iwocapay', value: 'Iwocapay'},
  {id: 'external_kbc', value: 'KBC'},
  {id: 'external_nexi_pay', value: 'Nexi Pay'},
  {id: 'external_oney', value: 'Oney'},
  {id: 'external_payconiq', value: 'Payconiq'},
  {id: 'external_paypo', value: 'PayPo'},
  {id: 'external_pledg', value: 'Pledg'},
  {id: 'external_postepay', value: 'Postepay'},
  {id: 'external_postfinance', value: 'PostFinance'},
  {id: 'external_scalapay', value: 'Scalapay'},
  {id: 'external_truelayer', value: 'TrueLayer'},
  {id: 'external_walley', value: 'Walley'},
  {id: 'external_younited_pay', value: 'YounitedPay'},
  {id: 'external_line_pay', value: 'LINE Pay'},
  {id: 'external_paysafecard', value: 'paysafecard'},
  {id: 'external_samsung_pay', value: 'Samsung Pay'},
  {id: 'external_sezzle', value: 'Sezzle'},
  {id: 'external_dapp', value: 'Dapp'},
  {id: 'external_picpay', value: 'PicPay'},
  {id: 'external_tabby', value: 'Tabby'},
  {id: 'external_benefit', value: 'Benefit'},
  {id: 'external_fawry', value: 'Fawry'},
  {id: 'external_paypal', value: 'PayPal'},
  {id: 'external_venmo', value: 'Venmo'},
];
