name: 'Build and Deploy to Cloud Run'

on:
  workflow_dispatch:
    inputs:
      subdomain:
        description: 'What subdomain would you like to deploy to?'
        required: true
      environment:
        type: environment
        description: 'Deployment type (typically Custom)'
        default: 'custom'
        required: true
      custom_env_file:
        type: string
        description: 'Paste your .env file (custom deployments only)'
        required: false
        default: ''
      persistent:
        type: boolean
        description: 'Keep this demo active perpetually? (Not necessary for most demos)'
        required: false
        default: false

jobs:
  deploy:
    uses: stripe-demos/demoeng-ci/.github/workflows/deploy-cloud-run-service.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      environment: ${{ github.event.inputs.environment }}
      subdomain: ${{ github.event.inputs.subdomain }}
      custom_env_file: ${{ github.event.inputs.custom_env_file }}
      persistent: ${{ github.event.inputs.persistent }}
      region: us-central1
    secrets: inherit
